### ISSUE TITLE
mising models: ./nets/detnet_s1.mat, ./nets/detnet_s2.mat and ./nets/detnet_s4.mat

### ISSUE THREAD

**Issue by HubYZ** [lenck/ddet#1]
there are no models in ./nets folder.

**Comment by HubYZ** [comment]
and there is nothing in the file ./nets/nets.url

**Comment by lenck** [comment]
Hi, they are downloaded as binary blobs with running setup.m...

**Comment by lenck** [comment]
Ah, that's a bug then... Can't fix it now, though :/
But the networks are at:
http://www.robots.ox.ac.uk/~karel/blobs/ddet-nets.tar.gz

**Comment by lenck** [comment]
Hi, should be fixed now. Also fixed a big in MatConvNet master which made it crash as well... 

Hope it works now.
